#! /bin/sh

fc-cache -fv &
xsetroot -cursor_name left_ptr
setxkbmap -layout us,ir &
/usr/bin/lxpolkit &
sxhkd &
nitrogen --restore &
flameshot &

# polybar

# ~/.config/polybar/launch.sh --colorblocks &


# compositing and wallpaper 

picom & 
#feh --bg-fill ~/Pictures/wall/gruv.png &
#xrdb merge ~/.Xresources &  # (terminal theme)

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          8
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a arduino state=floating
#bspc rule -a /usr/bin/lxpolkit state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc config top_padding 0

# border colors 
bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"


