#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
setxkbmap -layout us,ir &
picom &
xsetroot -cursor_name left_ptr

bspc monitor -d 一 二 三 四 五 六 七 八

bspc config border_width 2
bspc config window_gap 8

#bspc config top_padding 	8
bspc config left_padding 53
bspc config right_padding 4
#bspc config bottom_padding 	2

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a xfce4-whiskermenu-plugin state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
