#! /bin/sh

my_laptop_external_monitor=$(xrandr --query | grep 'VGA-1')
if [[ $my_laptop_external_monitor = 'VGA-1 connected (normal left inverted right x axis y axis)' ]]; then
    echo 'dual'
    bspc monitor VGA-1 -d 1 2 3
    bspc monitor LVDS-1 -d 4 5 6
else
    echo 'single'
    bspc monitor -d 1 2 3 4 5 6
fi
